"use client";

import Image from "next/image";
import { useEffect, useState } from "react";

interface Variant {
  slug: string;
  label: string;
  path: string;
}

interface Manifest {
  generatedAt: string;
  variants: Variant[];
}

const LAYOUTS = [
  { key: "floating-panels", label: "Floating panels (current)" },
  { key: "three-pane-shell", label: "Three-pane Discord shell" },
  { key: "left-rail-only", label: "Linear-style left rail" },
  { key: "canvas-first", label: "Owlbear minimalist" },
];

const AESTHETICS = [
  { key: "restrained", label: "Restrained (Linear)" },
  { key: "theatrical", label: "Theatrical (D&D)" },
];

export default function DesignMockups() {
  const [manifest, setManifest] = useState<Manifest | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [focused, setFocused] = useState<Variant | null>(null);

  useEffect(() => {
    fetch("/design-mockups/manifest.json")
      .then((r) => {
        if (!r.ok) throw new Error(`manifest ${r.status}`);
        return r.json();
      })
      .then(setManifest)
      .catch((e) => setError(String(e)));
  }, []);

  const find = (layoutKey: string, aesKey: string) =>
    manifest?.variants.find((v) => v.slug === `${layoutKey}__${aesKey}`);

  return (
    <main className="min-h-screen bg-background text-foreground px-6 py-10">
      <header className="max-w-7xl mx-auto mb-6">
        <p className="text-[11px] uppercase tracking-[0.4em] text-muted-foreground mb-1">
          Daggor · design mockups
        </p>
        <h1 className="text-3xl font-bold tracking-tight">UI alternatives</h1>
        <p className="text-sm text-muted-foreground mt-2 max-w-3xl">
          4 layouts × 2 aesthetics, generated by gpt-image-2. Click any image to
          enlarge. These are <span className="text-foreground">visual references</span>,
          not pixel-perfect targets &mdash; once you pick one, I&apos;ll
          implement the layout/aesthetic, not literally reproduce the image.
        </p>
        {manifest && (
          <p className="text-[11px] text-muted-foreground mt-1">
            Generated {new Date(manifest.generatedAt).toLocaleString()}
          </p>
        )}
      </header>

      {error && (
        <div className="max-w-7xl mx-auto rounded-md border border-destructive bg-destructive/10 px-4 py-3 text-sm">
          Failed to load manifest: {error}
        </div>
      )}

      {manifest && (
        <div className="max-w-7xl mx-auto">
          {/* Column headers */}
          <div className="grid grid-cols-[160px_1fr_1fr] gap-3 mb-2 px-2">
            <div />
            {AESTHETICS.map((a) => (
              <div
                key={a.key}
                className="text-[11px] uppercase tracking-[0.25em] text-muted-foreground"
              >
                {a.label}
              </div>
            ))}
          </div>
          {/* Rows: one per layout, two columns of aesthetics */}
          <div className="flex flex-col gap-4">
            {LAYOUTS.map((layout) => (
              <div
                key={layout.key}
                className="grid grid-cols-[160px_1fr_1fr] gap-3 items-start"
              >
                <div className="text-sm font-medium pt-3 px-2 text-foreground">
                  {layout.label}
                </div>
                {AESTHETICS.map((a) => {
                  const v = find(layout.key, a.key);
                  if (!v) {
                    return (
                      <div
                        key={a.key}
                        className="aspect-video rounded-lg border border-dashed border-border bg-card/40 flex items-center justify-center text-xs text-muted-foreground"
                      >
                        missing
                      </div>
                    );
                  }
                  return (
                    <button
                      key={a.key}
                      type="button"
                      onClick={() => setFocused(v)}
                      className="group relative aspect-video rounded-lg overflow-hidden border border-border bg-card hover:border-primary/60 transition-colors"
                      title={v.label}
                    >
                      <Image
                        src={v.path}
                        alt={v.label}
                        fill
                        unoptimized
                        sizes="(max-width: 1280px) 50vw, 600px"
                        className="object-cover"
                      />
                      <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/85 via-black/40 to-transparent p-3 opacity-0 group-hover:opacity-100 transition-opacity">
                        <p className="text-xs text-white">{v.label}</p>
                        <p className="text-[10px] text-white/70 mt-0.5">
                          Click to enlarge
                        </p>
                      </div>
                    </button>
                  );
                })}
              </div>
            ))}
          </div>

          <p className="mt-8 text-sm text-muted-foreground max-w-3xl">
            Once you pick a winner, tell me the slug
            (<code className="font-mono text-xs">layout-key__aesthetic-key</code>)
            and I&apos;ll start implementing it on top of the Phase 1 token system.
            Combinations to consider: many people pair a structured layout
            (three-pane / left-rail) with the Restrained aesthetic, and reserve
            the Theatrical look for the projector view only.
          </p>
        </div>
      )}

      {/* Lightbox */}
      {focused && (
        <button
          type="button"
          onClick={() => setFocused(null)}
          className="fixed inset-0 z-50 bg-background/95 backdrop-blur-sm flex flex-col items-center justify-center p-6 cursor-zoom-out"
        >
          <div className="relative max-w-[95vw] max-h-[88vh] w-[1600px] aspect-video rounded-lg overflow-hidden border border-border">
            <Image
              src={focused.path}
              alt={focused.label}
              fill
              unoptimized
              sizes="95vw"
              className="object-contain"
              priority
            />
          </div>
          <p className="mt-4 text-sm text-foreground">{focused.label}</p>
          <p className="mt-1 text-[11px] text-muted-foreground">
            Click anywhere to close
          </p>
        </button>
      )}
    </main>
  );
}
